//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cadastro_produtos
    {
        public long id { get; set; }
        public string tipo { get; set; }
        public string nomenclatura { get; set; }
        public int unidade_caixa { get; set; }
        public decimal peso { get; set; }
    }
}
